### ISSUE TITLE
Data service is unavailable

### ISSUE THREAD

**Issue by applefl** [joaofig/dublin-bus#1]
I try to download data from http://opendata.dublincity.ie/TrafficOpenData/sir010113-310113.zip. However, it returns "HTTP Error 503: Service Unavailable"

**Comment by joaofig** [comment]
This seems to be a problem with the provider. The home page is:
https://data.smartdublin.ie/dataset/dublin-bus-gps-sample-data-from-dublin-city-council-insight-project
I'm not really sure about what can be done about this, apart from contacting the site.

**Comment by applefl** [comment]
Thanks for response. I'll try to find other data sources.

**Comment by joaofig** [comment]
The data is back online! The download process is excruciatingly slow, but works.

**Comment by applefl** [comment]
I have found an alternative dataset, thank you anyway.
